exports.mainPage = function(d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Vault</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Compositor Management</h1>
                </header>
                <div class="w3-container">
                    <p>
                        <a href="/compositores">Compositores</a>
                    </p>
                    <p>
                        <a href="/periodos">Periodos</a>
                    </p>
                </div>
                <footer class="w3-container w3-teal">
                    <h5>Gerado por EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodosListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos List</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Periodos List
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Periodo</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>
                        <a href="/periodos/${slist[i].id}">${slist[i].id}</a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${slist[i].id}">Edit</a>]
                        [<a href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Gerado por EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoPage = function( periodo, compositores, d){
    var pagHTML = `
    <html>
    <head>
        <title>${periodo}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>${periodo}</h1>
            </header>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
                    <li><b>Compositores</b></li>
                    <ul>
    `
    for(let i=0; i < compositores.length ; i++){
        pagHTML += `
                    <li>
                        <a href="/compositores/${compositores[i].id}">${compositores[i].nome}</a>
                    </li>
        `
    }

    pagHTML += `
                    </ul>
                </ul>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/periodos">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.periodoFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodo Form</h2>
                </header>
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <!-- Add other fields for period data here -->
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
}

exports.periodoFormEditPage = function(data, d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodo Form</h2>
                </header>
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${data.id}"/>
                        <!-- Add other fields for period data here -->
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
}

exports.composersListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Compositores List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>id</th><th>nome</th><th>bio</th>
                            <th>Actions</th><th>dataNasc</th><th>dataObito</th>
                            <th>periodo</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">${slist[i].nome}</a>
                    </td>
                    <td>${slist[i].bio}</td>
                    <td>${slist[i].dataNasc}</td>
                    <td>${slist[i].dataObito}</td>
                    <td>${slist[i].periodo}</td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>]
                        [<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Gerado por EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositorFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Birthday Date</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Death Date</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024
                     in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                        <label>Birthday Date</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${a.dataNasc}"/>
                        <label>Death Date</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${a.dataObito}"/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${a.periodo}"/>
                    </fieldset>
  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>   
            </div>
    `
    return pagHTML
}

exports.compositorPage = function( compositor, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Name: </b> ${compositor.nome}</li>
                    <li><b>Bio: </b> ${compositor.bio}</li>
                    <li><b>Birthday Date: </b> ${compositor.dataNasc}</li>
                    <li><b>Death Date: </b> ${compositor.dataObito}</li>
                    <li><b>Period: </b> ${compositor.periodo}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            
    
            </ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/compositores">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.editConfirmPage = function(d){
    return `
    <html>
    <head>
        <title>Changes</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Changes</h1>
            </header>
            <div class="w3-container">
                <p>Changes were successfully made.</p>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.deleteConfirmPage = function(){
    return `
    <html>
    <head>
        <title>Changes</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Changes</h1>
            </header>
            <div class="w3-container">
                <p>Entry was successfully deleted.</p>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por EngWeb2024 - [<a href="/">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.registoConfirmPage = function(d){
    return `
    <html>
    <head>
        <title>Changes</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Changes</h1>
            </header>
            <div class="w3-container">
                <p>Entry was successfully registered.</p>
            </div>
            <footer class="w3-container w3-teal">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}